### ISSUE TITLE
Back button on machine detail page behaves unexpectedly

### ISSUE THREAD

**Issue by yagmot** [salsoftware/sal#65]
Instead of going back to the list you were viewing (i.e. clients with errors or clients with warnings), the back button on the machine detail page takes you to the dashboard.

**Comment by grahamgilbert** [comment]
I'm not opposed to changing this, but here's the reason behind this decision:

Sal operates on a hierarchy - you have the top level -> Business Units -> Machines Groups -> Machines - the back button merely takes you back up a level. This is simply because it was easier to code, so I'm happy to take pull requests that will fix this.

**Comment by henrydobson** [comment]
No longer maintained here
